### PR TITLE
Respect stacked borrows when polling

### PR DESCRIPTION
**Pull request by eholk**
Polling the wrapped future previously had several reborrow operations, such as in the use of `map_unchecked_mut` and in the implementation of `as_mut_ptr`. This caused issues when running under miri in the `stress_drop_sender` test.

This change re-implements these problematic cases to avoid reborrows, either through using `Pin::get_unchecked_mut` or transmuting pointers rather than borrowing and casting.

Fixes https://github.com/microsoft/stackfuture/issues/9

### CODE REVIEW

**Comment by daprilik** [comment]
As much as I'd love to rubber-stamp this PR, I'm not all too familiar with stacked borrow rules myself, so i'll leave it to Wesley to sign off here.

**Comment by yoshuawuyts** [comment]
I see Miri is enabled on CI, but the docs mention stacked borrows is still experimental — does Miri in CI here validate against the stacked borrows rules, or does that need to be enabled somehow?

**Comment by eholk** [comment]
I've just been running Miri in the default settings and was able to repro the bug locally. We're using the defaults in CI too, so we should be good there too.

**Comment by yoshuawuyts** [comment]
Gotcha! Yay, great!

**Review by wesleywiser — APPROVED** [review]
Looks good to me!

**Comment by wesleywiser** [comment]
> I see Miri is enabled on CI, but the Miri docs mention stacked borrows is still experimental — does Miri in CI here validate against the stacked borrows rules, or does that need to be enabled somehow?

Stacked borrows is the model used to detect aliasing violations so it's enabled by default. There's actually an option to *disable* it `-Zmiri-disable-stacked-borrows`.

**Pull request merged**
