### PR TITLE
Add description and repository fields to Cargo.toml

### PR DESCRIPTION
**Pull request by eholk**
I'm getting ready to push our first release to crates.io and it'd be better if we had these fields set first.

### CODE REVIEW

**Review by daprilik — APPROVED** [review]

**Comment by daprilik** [comment]
Consider adding some more "advertising" fields as well (e.g: see gdbstub: https://github.com/daniel5151/gdbstub/blob/master/Cargo.toml#L8-L13)

**Comment by eholk** [comment]
> Consider adding some more "advertising" fields as well (e.g: see gdbstub: https://github.com/daniel5151/gdbstub/blob/master/Cargo.toml#L8-L13)

Good idea, I added a few. Do you think there are any others I should add?

**Comment by eholk** [comment]
The `documentation` and `readme` fields get set to what we want by default, so I chose to leave those off.

**Comment by daprilik** [comment]
IIRC, `readme` and `documentation` both correspond to their respective buttons on crates.io.
IMO, the docs one is pretty important, as that's how I usually land on docs for a crate. 

Also - not entirely related to this PR - but consider adding some links (and/or badges) to the README.md that link to docs.rs/crates.io.

* * *

I know it feels weird to add "dead links" before the crate is published, but if you don't, you'll just end up having to publish a minor version of the lib to update the README, which I think is kinda silly

**Comment by eholk** [comment]
> wait, whaaaat? since when??

Not sure, but here's the documentation: https://doc.rust-lang.org/cargo/reference/manifest.html#the-documentation-field

> Also - not entirely related to this PR - but consider adding some links (and/or badges) to the README.md that link to docs.rs/crates.io.

Yeah, I think this would be good. I'll wait until we get the crate published so we actually have something to link to though :)

**Comment by daprilik** [comment]
> > wait, whaaaat? since when??
> 
> Not sure, but here's the documentation: https://doc.rust-lang.org/cargo/reference/manifest.html#the-documentation-field

huh, the more you know.

* * *

I think this LGTM, feel free to send it 🚀

**Pull request merged**
